<VentanaTerminales>:
    #name: "third"
    GridLayout:
        cols:1
         
        GridLayout:
        
            cols:2
        Button:
            size_hint_y: 0.1
            size_hint_x: 0.1
            text: "Atrás"
            on_release: 
                app.root.current= "ventanaselori_dest"
        Button:
            size_hint_y: 0.1
            size_hint_x: 0.1
            text: "siguiente ventana"
            on_release: 
                app.root.current= "ventana_empresas"